name: Cypress Tests

on:
  pull_request:
    branches: [develop]

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Component Tests
        run: npx cypress run --component

      - name: Start app for E2E tests
        run: npm run dev &
        working-directory: client

      - name: Wait for app to be ready
        run: npx wait-on http://localhost:3001

      - name: Run E2E Tests
        run: npx cypress run --e2e
